# Generated by Django 4.0 on 2021-12-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('project_image', models.ImageField(upload_to='images')),
                ('project_link', models.URLField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
