# Generated by Django 4.0 on 2021-12-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_revieww'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revieww',
            new_name='Review',
        ),
    ]
